python train_augment.py \
    --agent bisim \
    --replay_buffer_capacity 1000 \
    --num_train_steps 100 \
    --batch_size 16 \
    --num_eval_episodes 3 \
    --domain_name cheetah \
    --task_name run \
    --encoder_type pixel \
    --decoder_type identity \
    --action_repeat 4 \
    --save_video \
    --save_tb \
    --work_dir ./exp/bmv_test \
    --seed 1 \